# Generated by Django 5.2.3 on 2025-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(help_text='Site name', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(help_text='Site URL', max_length=100),
        ),
    ]
