# Generated by Django 5.2.3 on 2025-06-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_baskets', to='customers.customers'),
        ),
    ]
