# Generated by Django 5.2.3 on 2025-06-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
